import Head from "next/head";
import React from "react";

const PageHead = ({ title }: { title?: string }) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/union.png" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
    </Head>
  );
};

export default PageHead;
